<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="NUnit" Version="5.0.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="6.3.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DshDesktop\DshDesktop.csproj" />
		<ProjectReference Include="..\DshDesktop.Core\DshDesktop.Core.csproj" />
		<ProjectReference Include="..\DshDesktop.Infrastructure\DshDesktop.Infrastructure.csproj" />
	</ItemGroup>
</Project>
