using DshDesktop.Harness.Models.Requests;
using DshDesktop.Harness.Models.Responses;
using DshDesktop.Harness.Models.Rpc;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DshDesktop.Harness.Json;

/// <summary>协议序列化的源生成上下文；全部走显式类型信息，无反射。</summary>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
                             DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(SessionListRequest))]
[JsonSerializable(typeof(SessionCreateRequest))]
[JsonSerializable(typeof(SessionForkRequest))]
[JsonSerializable(typeof(SessionRenameRequest))]
[JsonSerializable(typeof(SessionPromptRequest))]
[JsonSerializable(typeof(SessionCancelRequest))]
[JsonSerializable(typeof(SessionFollowRequest))]
[JsonSerializable(typeof(SessionPageRequest))]
[JsonSerializable(typeof(SessionProjectionsRequest))]
[JsonSerializable(typeof(SessionSelectModelRequest))]
[JsonSerializable(typeof(SessionModelCatalogRequest))]
[JsonSerializable(typeof(WorkspaceCreateRequest))]
[JsonSerializable(typeof(WorkspaceArchiveSessionRequest))]
[JsonSerializable(typeof(WorkspaceRenameRequest))]
[JsonSerializable(typeof(WorkspaceDeleteRequest))]
[JsonSerializable(typeof(CommandExecuteRequest))]
[JsonSerializable(typeof(SettingsUpdateRequest))]
[JsonSerializable(typeof(SettingsReplaceRequest))]
[JsonSerializable(typeof(SettingsMutateRequest))]
[JsonSerializable(typeof(SettingsOpRequest))]
[JsonSerializable(typeof(CredentialsSetRequest))]
[JsonSerializable(typeof(CredentialsUnsetRequest))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(SessionListValue))]
[JsonSerializable(typeof(SessionCreateValue))]
[JsonSerializable(typeof(SessionForkValue))]
[JsonSerializable(typeof(SessionRenameValue))]
[JsonSerializable(typeof(SessionAcceptedValue))]
[JsonSerializable(typeof(SessionPageValue))]
[JsonSerializable(typeof(SessionProjectionsValue))]
[JsonSerializable(typeof(SessionSelectModelValue))]
[JsonSerializable(typeof(SessionModelCatalogValue))]
[JsonSerializable(typeof(SessionModelSelectionWire))]
[JsonSerializable(typeof(ModelProviderGroupWire))]
[JsonSerializable(typeof(ModelCatalogModelWire))]
[JsonSerializable(typeof(ModelReasoningWire))]
[JsonSerializable(typeof(ModelReasoningEffortWire))]
[JsonSerializable(typeof(ModelCatalogFailureWire))]
[JsonSerializable(typeof(SessionSummaryWire))]
[JsonSerializable(typeof(SessionProjectionHintsWire))]
[JsonSerializable(typeof(WorkspaceCreateValue))]
[JsonSerializable(typeof(WorkspaceArchiveValue))]
[JsonSerializable(typeof(WorkspaceRenameValue))]
[JsonSerializable(typeof(WorkspaceDeleteValue))]
[JsonSerializable(typeof(CredentialInfoWire))]
[JsonSerializable(typeof(Dictionary<string, CredentialInfoWire>))]
[JsonSerializable(typeof(CommandExecuteValue))]
[JsonSerializable(typeof(PermissionCatalogWire))]
[JsonSerializable(typeof(PermissionPresetOptionWire))]
[JsonSerializable(typeof(SettingsDescribeValueWire))]
[JsonSerializable(typeof(SettingsNamespaceViewWire))]
[JsonSerializable(typeof(SettingsOpenDocumentValue))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(RpcRequestEnvelope))]
[JsonSerializable(typeof(MuxOpenMessage))]
[JsonSerializable(typeof(MuxCancelMessage))]
[JsonSerializable(typeof(StreamPayloadWire))]
[JsonSerializable(typeof(EventsResultRequest))]
public sealed partial class HarnessJsonContext : JsonSerializerContext;
